server:
  port: 8090
eureka:
  client:
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://discovery:8001/eureka/
zuul:
  prefix: /glarimy
  routes:
    employee-service:
      path: /employee/**
      serviceId: employee-service
    static:
      path: /home/**
spring:
  application:
    name: zuul-server
